version: 2
updates:
  - package-ecosystem: npm
    directory: /
    registries: "*"
    schedule:
      interval: weekly
    reviewers:
      - env-iron/dependabot-reviewers
  - package-ecosystem: github-actions
    directory: /
    registries: "*"
    schedule:
      interval: weekly
    reviewers:
      - env-iron/dependabot-reviewers
